// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL6lc-YJvKSh4B2bnjbN4eDXq8t_JU39Y',
    appId: '1:666383994372:web:36bd861d3a09d973a9af51',
    messagingSenderId: '666383994372',
    projectId: 'rental-84586',
    authDomain: 'rental-84586.firebaseapp.com',
    storageBucket: 'rental-84586.appspot.com',
    measurementId: 'G-8HR92E85PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdXcxlSPAX2GpXSuGqtD6iGknQwEyo0wg',
    appId: '1:666383994372:android:e52462091ad6b5f5a9af51',
    messagingSenderId: '666383994372',
    projectId: 'rental-84586',
    storageBucket: 'rental-84586.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChbwuMl5Z-DMYs9XsZWIF2nK8Lh50-v6s',
    appId: '1:666383994372:ios:90a04d8f65de316fa9af51',
    messagingSenderId: '666383994372',
    projectId: 'rental-84586',
    storageBucket: 'rental-84586.appspot.com',
    iosBundleId: 'com.example.rentcar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChbwuMl5Z-DMYs9XsZWIF2nK8Lh50-v6s',
    appId: '1:666383994372:ios:60e0523fc6fc6ac9a9af51',
    messagingSenderId: '666383994372',
    projectId: 'rental-84586',
    storageBucket: 'rental-84586.appspot.com',
    iosBundleId: 'com.example.rentcar.RunnerTests',
  );
}
